"""Generate LaTeX table fragments for the paper from results/*.json.

Every number in the paper's tables comes from committed result files — never typed by hand.
Run:  .venv/bin/python -m conditional_operators.gen_tables
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "results"
OUT = ROOT / "docs" / "paper" / "tables"

ARMS = ["film", "concat_mlp", "cond_layernorm", "hypernet", "dynamic_linear",
        "proposed_mlp_gs", "proposed"]
LABEL = {
    "film": "FiLM", "concat_mlp": "Concat-MLP", "cond_layernorm": "Cond-LN",
    "hypernet": "Hypernetwork", "dynamic_linear": "Dyn.\\ low-rank",
    "proposed_mlp_gs": "MLP-head (abl.)", "proposed": "\\textbf{Lie (ours)}",
}
STAGES = [
    ("summary.json", "S1"),
    ("stage3_summary.json", "S2"),
    ("stage4_summary.json", "S3"),
    ("stage4b_summary.json", "S3b"),
    ("stage5_summary.json", "S4"),
]


def _load(name):
    p = R / name
    return json.loads(p.read_text()) if p.exists() else None


def _sig(x, std=None):
    if x is None:
        return "--"
    s = f"{x:.1e}".replace("e-0", "e-").replace("e+0", "e+")
    mant, exp = s.split("e")
    cell = f"${mant}\\!\\times\\!10^{{{int(exp)}}}$"
    return cell


def main_table() -> str:
    stages = [(k, t, _load(k)) for k, t in STAGES]
    stages = [(k, t, s) for k, t, s in stages if s]
    cols = "l" + "c" * len(stages)
    head = " & ".join(t for _, t, _ in stages)
    rows = []
    for a in ARMS:
        cells = []
        for _, _, s in stages:
            pa = s["per_arm"].get(a)
            cells.append(_sig(pa["ood_test_mean"]) if pa else "--")
        rows.append(f"{LABEL[a]} & " + " & ".join(cells) + r" \\")
    body = "\n".join(rows)
    stats = []
    for _, t, s in stages:
        stats.append(f"{t}: {s.get('margin_observed', 0)*100:.0f}\\% vs.\\ "
                     f"{s.get('best_unstructured','?').replace('_','-')}"
                     f" ($p={s.get('p_value',0):.0e}$)".replace("e-0", "e-"))
    caption_stats = "; ".join(stats)
    return (
        "% AUTO-GENERATED by gen_tables.py — do not edit\n"
        "\\begin{tabular}{" + cols + "}\n\\toprule\n"
        "Conditioner & " + head + r" \\" + "\n\\midrule\n" + body +
        "\n\\bottomrule\n\\end{tabular}\n"
        "% gate margins: " + caption_stats + "\n")


def budget_table() -> str:
    s = _load("stage4_summary.json")
    rows = []
    for a in ARMS:
        pa = s["per_arm"].get(a)
        if not pa:
            continue
        rows.append(f"{LABEL[a]} & {pa['params']:,} & {pa['flops_vs_film']:.2f}$\\times$ \\\\")
    return (
        "% AUTO-GENERATED by gen_tables.py — do not edit\n"
        "\\begin{tabular}{lrr}\n\\toprule\n"
        "Conditioner & Params & FLOPs vs.\\ FiLM \\\\\n\\midrule\n" +
        "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def ratio_table() -> str:
    stages = [(k, t, _load(k)) for k, t in STAGES[2:]]     # real-image stages only
    stages = [(k, t, s) for k, t, s in stages if s]
    cols = "l" + "c" * len(stages)
    head = " & ".join(t for _, t, _ in stages)
    rows = []
    for a in ARMS:
        cells = []
        for _, _, s in stages:
            pa = s["per_arm"].get(a)
            cells.append(f"{pa['ood_test_mean']/pa['indist_mean']:.2f}$\\times$" if pa else "--")
        rows.append(f"{LABEL[a]} & " + " & ".join(cells) + r" \\")
    return (
        "% AUTO-GENERATED by gen_tables.py — do not edit\n"
        "\\begin{tabular}{" + cols + "}\n\\toprule\n"
        "Conditioner & " + head + r" \\" + "\n\\midrule\n" + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "main_results.tex").write_text(main_table())
    (OUT / "budget.tex").write_text(budget_table())
    (OUT / "ratio.tex").write_text(ratio_table())
    print("wrote", *[OUT / f for f in ("main_results.tex", "budget.tex", "ratio.tex")])
